version: '3.9'
services:
  web:
    container_name: leMien
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./myAPP:/app"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
volumes:
  db_data:
